[package]
name = "gilded-university-server"
version = "0.1.0"
edition = "2021"
license = "MIT"
author = "Benyakir Horowitz"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.15.10"
juniper_warp = "0.7.0"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.18"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
warp = { version = "0.3.2", default-features = false }