name: Integration Tests
on: [push, pull_request]

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: gutests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run integration tests
        uses: actions-rs/cargo@v1
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/gutests
        with:
          command: test
          args: integration_ -- --test-threads 1
